# Person
+ name (string) - The Parson's name

# Company
+ name Apiary
+ founder (Person)
+ founded: 2011 (number) - The year in which the commpany was founded
+ address
	+ street: 235 Ninth Street
	+ city: San Francisco
	+ state: California

# Administrator (Person)
+ role (string) - The adminstrators role
